// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbiccrntustnvgovuqmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiaWNjcm50dXN0bnZnb3Z1cW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzY0MjgsImV4cCI6MjA2ODk1MjQyOH0.cKeLrYOSyDXt5kqvkAUvzRNj0U-mIffhXDkgtE8MQfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});